return {
  version = "1.9",
  luaversion = "5.1",
  tiledversion = "1.9.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 8,
  height = 8,
  tilewidth = 52,
  tileheight = 52,
  nextlayerid = 18,
  nextobjectid = 36,
  properties = {},
  tilesets = {
    {
      name = "tileset",
      firstgid = 1,
      class = "",
      tilewidth = 52,
      tileheight = 52,
      spacing = 0,
      margin = 0,
      columns = 4,
      image = "map-tileset/groundFloorHallTileset.png",
      imagewidth = 208,
      imageheight = 364,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 52,
        height = 52
      },
      properties = {},
      wangsets = {},
      tilecount = 28,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 8,
      height = 8,
      id = 1,
      name = "background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 8,
      height = 8,
      id = 2,
      name = "ground",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 2, 2, 2, 2, 0, 0,
        0, 2, 2, 2, 2, 2, 0, 0,
        0, 0, 2, 2, 2, 2, 0, 0,
        0, 0, 2, 2, 2, 2, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 8,
      height = 8,
      id = 3,
      name = "walls",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 3, 3, 3, 3, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 8,
      height = 8,
      id = 4,
      name = "walldetails",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 17, 17, 17, 17, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 8,
      height = 8,
      id = 5,
      name = "roomborder",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 13, 24, 24, 24, 24, 14, 0,
        0, 23, 9, 0, 0, 10, 22, 20,
        20, 23, 0, 0, 0, 0, 0, 20,
        20, 20, 20, 0, 0, 0, 22, 20,
        20, 23, 0, 0, 0, 0, 22, 0,
        0, 23, 11, 0, 0, 12, 22, 0,
        0, 15, 21, 21, 21, 21, 16, 0,
        0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 8,
      height = 8,
      id = 9,
      name = "roomborder2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 24, 20,
        0, 24, 0, 0, 0, 0, 0, 20,
        0, 0, 0, 0, 0, 0, 21, 20,
        0, 21, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 8,
      height = 8,
      id = 7,
      name = "door",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = -11.6589,
      offsety = 12,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 25, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 8,
      height = 8,
      id = 8,
      name = "upstairs",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 26, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 8,
      height = 8,
      id = 10,
      name = "cabinet",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 13.6667,
      offsety = 2.33333,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 4, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 8,
      height = 8,
      id = 11,
      name = "clotheshanger",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = -10.6667,
      offsety = -73.6667,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 5, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 8,
      height = 8,
      id = 12,
      name = "sofa",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = -15.6667,
      offsety = 0.666667,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 7, 8, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 8,
      height = 8,
      id = 13,
      name = "tv",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 12,
      offsety = 3,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 6, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 8,
      height = 8,
      id = 14,
      name = "carpet",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = -2.66667,
      offsety = 7.66667,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 27, 28, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 8,
      height = 8,
      id = 15,
      name = "fireplace",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 19, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 20, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 16,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "cabinet",
          class = "",
          shape = "rectangle",
          x = 292.696,
          y = 173.391,
          width = 16.9565,
          height = 22.9565,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "tv",
          class = "",
          shape = "rectangle",
          x = 220.188,
          y = 271.125,
          width = 50.75,
          height = 35.875,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "sofa",
          class = "",
          shape = "rectangle",
          x = 212.25,
          y = 221.75,
          width = 63,
          height = 27.8125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "clotheshanger",
          class = "",
          shape = "rectangle",
          x = 108.273,
          y = 90.0909,
          width = 18,
          height = 33.4545,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 98.4375,
          y = 312,
          width = 219.313,
          height = 5.8125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 311.875,
          y = 156.25,
          width = 5.875,
          height = 161.625,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 312,
          y = 156,
          width = 57.8182,
          height = 6.18182,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 364.364,
          y = 98.1818,
          width = 5.63636,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 98.1136,
          y = 98,
          width = 272.068,
          height = 5.81818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 98,
          y = 97.75,
          width = 5.75,
          height = 57.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 46,
          y = 149.636,
          width = 57.6364,
          height = 6.36364,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 45.6364,
          y = 149.091,
          width = 6.18182,
          height = 65.0909,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 45.4545,
          y = 208.182,
          width = 58.7273,
          height = 5.81818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "wall",
          class = "",
          shape = "rectangle",
          x = 97.8182,
          y = 208.182,
          width = 6.36364,
          height = 109.455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "fireplace",
          class = "",
          shape = "rectangle",
          x = 208.125,
          y = 51.875,
          width = 51.875,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 17,
      name = "queryBoxs",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 20,
          name = "clotheshanger",
          class = "static",
          shape = "rectangle",
          x = 110.182,
          y = 123.636,
          width = 13.4545,
          height = 2.81818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "clotheshanger",
          class = "static",
          shape = "rectangle",
          x = 126.364,
          y = 105.182,
          width = 3.63636,
          height = 15.5455,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "kitchendoor",
          class = "teleport",
          shape = "rectangle",
          x = 167.727,
          y = 103.818,
          width = 13,
          height = 4.27273,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "exitdoor",
          class = "teleport",
          shape = "rectangle",
          x = 51.75,
          y = 156.25,
          width = 6.5,
          height = 51.75,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "fireplace",
          class = "static",
          shape = "rectangle",
          x = 213.364,
          y = 104,
          width = 42.5455,
          height = 4.81818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "sofa",
          class = "static",
          shape = "rectangle",
          x = 208.545,
          y = 233.727,
          width = 3.81818,
          height = 8.81818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "sofa",
          class = "static",
          shape = "rectangle",
          x = 219.375,
          y = 216.625,
          width = 48.75,
          height = 5.125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "sofa",
          class = "static",
          shape = "rectangle",
          x = 275.25,
          y = 233.875,
          width = 4.125,
          height = 9.625,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "sofa",
          class = "static",
          shape = "rectangle",
          x = 217,
          y = 249.5,
          width = 53.625,
          height = 4.75,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "tv",
          class = "static",
          shape = "rectangle",
          x = 223.875,
          y = 266.125,
          width = 43.625,
          height = 5.125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "tv",
          class = "static",
          shape = "rectangle",
          x = 215.25,
          y = 277.125,
          width = 4.875,
          height = 16.75,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "tv",
          class = "static",
          shape = "rectangle",
          x = 271.25,
          y = 277.125,
          width = 4.75,
          height = 17.125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "cabinet",
          class = "static",
          shape = "rectangle",
          x = 288.364,
          y = 176,
          width = 4.45455,
          height = 17.2727,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "cabinet",
          class = "static",
          shape = "rectangle",
          x = 295.364,
          y = 196.455,
          width = 13.0909,
          height = 3.90909,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "goingupstairs",
          class = "teleport",
          shape = "rectangle",
          x = 358.727,
          y = 103.909,
          width = 5.54545,
          height = 52.0909,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
