return {
  version = "1.9",
  luaversion = "5.1",
  tiledversion = "1.9.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 8,
  height = 8,
  tilewidth = 100,
  tileheight = 75,
  nextlayerid = 3,
  nextobjectid = 25,
  properties = {},
  tilesets = {
    {
      name = "bedroomTileset",
      firstgid = 1,
      class = "",
      tilewidth = 100,
      tileheight = 75,
      spacing = 0,
      margin = 0,
      columns = 8,
      image = "map.png",
      imagewidth = 800,
      imageheight = 600,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 100,
        height = 75
      },
      properties = {},
      wangsets = {},
      tilecount = 64,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 8,
      height = 8,
      id = 1,
      name = "Livello tile 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = -4.25,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        1, 2, 3, 4, 5, 6, 7, 8,
        9, 10, 11, 12, 13, 14, 15, 15,
        9, 18, 19, 20, 21, 22, 15, 15,
        9, 26, 27, 28, 29, 30, 15, 15,
        9, 34, 35, 36, 37, 38, 15, 15,
        9, 42, 43, 44, 45, 46, 15, 15,
        9, 50, 51, 52, 53, 54, 62, 62,
        9, 62, 62, 60, 61, 62, 62, 62
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "Walls",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "",
          class = "",
          shape = "rectangle",
          x = 176.75,
          y = 140.75,
          width = 59.5,
          height = 100.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          class = "",
          shape = "rectangle",
          x = 188.25,
          y = 250.75,
          width = 27.25,
          height = 32.75,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          class = "",
          shape = "rectangle",
          x = 174.5,
          y = 302.75,
          width = 56.25,
          height = 157.75,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          class = "",
          shape = "rectangle",
          x = 409,
          y = 145.75,
          width = 34.5,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          class = "",
          shape = "rectangle",
          x = 449.75,
          y = 64.25,
          width = 123.25,
          height = 133.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          class = "",
          shape = "rectangle",
          x = 520.5,
          y = 242.75,
          width = 60,
          height = 122.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          class = "",
          shape = "rectangle",
          x = 539.25,
          y = 430.25,
          width = 32.5,
          height = 25.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          class = "",
          shape = "rectangle",
          x = 168.5,
          y = 151.25,
          width = 8.25,
          height = 7.75,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          class = "",
          shape = "rectangle",
          x = 236.5,
          y = 151,
          width = 141,
          height = 7.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          class = "",
          shape = "rectangle",
          x = 377,
          y = 150.75,
          width = 32.25,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          class = "",
          shape = "rectangle",
          x = 443.75,
          y = 150.5,
          width = 6.25,
          height = 8.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          class = "",
          shape = "rectangle",
          x = 573.5,
          y = 151,
          width = 11.5,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          class = "",
          shape = "rectangle",
          x = 585,
          y = 293.75,
          width = 1.5,
          height = 177.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          class = "",
          shape = "rectangle",
          x = 585,
          y = 159,
          width = 2.25,
          height = 134.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          class = "",
          shape = "rectangle",
          x = 166.75,
          y = 159,
          width = 2,
          height = 141.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          class = "",
          shape = "rectangle",
          x = 166.75,
          y = 300.5,
          width = 2,
          height = 170.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          class = "",
          shape = "rectangle",
          x = 168.75,
          y = 471,
          width = 165,
          height = 2.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          class = "",
          shape = "rectangle",
          x = 334,
          y = 471.017,
          width = 42.75,
          height = 3.73333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          class = "",
          shape = "rectangle",
          x = 372.25,
          y = 475,
          width = 4.53125,
          height = 99.75,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          class = "",
          shape = "rectangle",
          x = 480.75,
          y = 471.25,
          width = 4.25,
          height = 104.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          class = "",
          shape = "rectangle",
          x = 485,
          y = 471,
          width = 102,
          height = 2.5,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
